### ISSUE TITLE
Fails to build RCurl from source on Windows

### ISSUE THREAD

**Issue by Aariq** [r-hub/actions#14]
Maybe this is an RCurl bug, but I figured I'd start here.  `rhub_check("https://github.com/Meredith-Lab/volcalc/", platforms = "windows", branch = "master")` is failing because of an error building `RCurl`: https://github.com/Meredith-Lab/volcalc/actions/runs/9023334902/job/24794891961

**Comment by gaborcsardi** [comment]
That is indeed an RCurl bug: https://cran.rstudio.com/web/checks/check_results_RCurl.html
