### ISSUE TITLE
clang-asan shows successful check even when UndefinedBehaviorSanitizer triggered

### ISSUE THREAD

**Issue by andrjohns** [r-hub/actions#16]
Just to wanted to check if this is expected/intended behaviour - when the `clang-asan` container detects undefined behaviour, the workflow still reports a successful completion. Should the workflow fail on detection, or is the intent to always inspect the output results? Thanks!

Can be seen in this run: https://github.com/andrjohns/QuickJSR/actions/runs/9077288982/job/24941850497

**Comment by gaborcsardi** [comment]
Thanks, that's a bug indeed.

**Comment by gaborcsardi** [comment]
I believe that this is now fixed: https://github.com/gaborcsardi/QuickJSR/actions/runs/9257833349/job/25466778924
