### ISSUE TITLE
configuring custom environment variables for the check

### ISSUE THREAD

**Issue by datapumpernickel** [r-hub/actions#18]
Hi,

first of all - this is amazing. Works like a charm! 

However, I cant wrap my head around how to configure the action to account for additional environment variables I want to set for the test, e.g. `_R_CHECK_THINGS_IN_OTHER_DIRS_ ` 

If I see correctly, these get parsed [here ](https://github.com/r-hub/actions/blob/main/check/action.yaml) on line 122. But I am not sure on which machine they have to be set (e.g. in the virtual machine) and how I can customize these. 

I am sorry if this is trivial, I would be happy, if you could point me in a direction. If it is not trivial, than it also is not very urgent and the issue can be closed. 

Thank you!

**Comment by gaborcsardi** [comment]
See https://docs.github.com/en/actions/learn-github-actions/variables#defining-environment-variables-for-a-single-workflow

**Comment by datapumpernickel** [comment]
Thanks for the link. That helped!

In the end, however, I think the environment variables were set in the r-lib/actions here directly to the R environment: https://github.com/r-lib/actions/blob/v2-branch/check-r-package/action.yaml 

```
runs:
  using: "composite"
  steps:
    - name: Check
      id: rcmdcheck
      run: |
        ## --------------------------------------------------------------------
        options(crayon.enabled = TRUE)
        cat("LOGNAME=", Sys.info()[["user"]], "\n", sep = "", file = Sys.getenv("GITHUB_ENV"), append = TRUE)
        if (Sys.getenv("_R_CHECK_FORCE_SUGGESTS_", "") == "") Sys.setenv("_R_CHECK_FORCE_SUGGESTS_" = "false")
        if (Sys.getenv("_R_CHECK_CRAN_INCOMING_", "") == "") Sys.setenv("_R_CHECK_CRAN_INCOMING_" = "false")

### CHANGES: 
#### HERE I ADDED: 
        Sys.setenv("_R_CHECK_THINGS_IN_OTHER_DIRS_" = "true")
### END OF CHANGES 

        cat("check-dir-path=", file.path(getwd(), (${{ inputs.check-dir }})), "\n", file = Sys.getenv("GITHUB_OUTPUT"), sep = "", append = TRUE)
        check_results <- rcmdcheck::rcmdcheck(args = (${{ inputs.args }}), build_args = (${{ inputs.build_args }}), error_on = (${{ inputs.error-on }}), check_dir = (${{ inputs.check-dir }}))
      shell: Rscript {0}
      working-directory: ${{ inputs.working-directory }}
```

I am not sure if this is the right place, but in terms of a feature request, it would be handy, if these variables could be set in the `rhub::rhub_setup()` command and be passed on through the yaml files, similar to how you can do this in `devtools::check()` with `devtools::check(env_vars = c("_R_CHECK_THINGS_IN_OTHER_DIRS_" = "true"))`. 

Feel free to close, as this is resolved per se.

**Comment by gaborcsardi** [comment]
We'll have a way to configure env vars in R-hub soon. Until then you can modify the `rhub.yaml` workflow file to add additional environment variables.

**Comment by datapumpernickel** [comment]
Cool! 

Ok, I think I now did understand it better. Magically worked by just setting:

```
      - uses: r-hub/actions/run-check@v1
        with:
          token: ${{ secrets.RHUB_TOKEN }}
          job-config: ${{ matrix.config.job-config }}
        env:
          _R_CHECK_THINGS_IN_OTHER_DIRS_: true
```

Because the env vars were set with Sys.setenv() in the orginal `check-r-package`-action.yaml I did not think setting it at this level would affect the CMD check, but it did!. 

Thank you again!

**Comment by datapumpernickel** [comment]
Reopening this because: 

1) When I specify an environment variable (\_R_CHECK_THINGS_IN_OTHER_DIRS\_ = true) in Windows the check errors out (i am really unsure how to debug this or where to start even) 

and 

2) it reports with a green check-mark nonetheless, which I guess is a bug? 

See: https://github.com/ropensci/comtradr/actions/runs/9205546360/job/25321458256 

All the best

**Comment by gaborcsardi** [comment]
1. This is not an issue that we can help with, the error is coming from the check code. AFAICT `file.info()` does not return an `"uname"` column on Windows, so I am not sure if this has ever worked on Windows.

2. This could be a bug, but most likely in the base R check code, which seems to exit with a successful status, even if an error happens:
   ```
   ❯ R CMD check /tmp/foo
   Warning: ‘/tmp/foo’ is neither a file nor directory, skipping
   
   ❯ echo $?
   0
   ```

**Comment by datapumpernickel** [comment]
Thanks, that helps. 

1. You are right, probably never has. I checked some older versions of the package that were accepted by CRAN and none pass this test and error out with the same error always. Thanks for the hint anyways, this leaves me a little calmer when submitting to CRAN. 

2. Ok, understand. Thanks for looking into this.

**Comment by gaborcsardi** [comment]
https://bugs.r-project.org/show_bug.cgi?id=18736
