### ISSUE TITLE
Configuration failed to find libraries - cairo system dependency for some old Linux distributions

### ISSUE THREAD

**Issue by m7pr** [r-hub/actions#24]
Thank you for creating all those excellent r-hub actions! I know there must be a lot of time and energy that have been invested to make this excellent project work. We are utilizing setup-r-dependencies for a couple of our packages!

Recently we stumbled upon an in issue where `cairo` system dependency can't be installed for a couple of old Linux distributions (but it can be installed for ubuntu-release and ubuntu-next). Would you have any clue why does that happen?

https://github.com/insightsengineering/teal.goshawk/actions/runs/11158031696/job/31013452052#step:7:6452
https://github.com/insightsengineering/teal.osprey/actions/runs/11158035445/job/31013465102#step:7:6524

```
 -----------------------------[ ANTICONF ]-------------------------------
6436 Configuration failed to find libraries. Try installing:
6437 * deb: libcairo2-dev (Debian, Ubuntu)
6438 * rpm: cairo-devel (Fedora, CentOS, RHEL)
6439 * csw: libcairo_dev (Solaris)
6440 * brew: cairo (OSX)
6441 If cairo freetype2 are already installed, check that 'pkg-config' is in your
6442 PATH and PKG_CONFIG_PATH contains a cairo freetype2.pc file. If pkg-config
6443 is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
6444 R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
```

Any advice to how to overcome this issue? Thanks for your time and for any response!

**Comment by gaborcsardi** [comment]
Both of them are fixed already:
https://github.com/insightsengineering/teal.goshawk/actions/runs/11161819395/job/31217734588
https://github.com/insightsengineering/teal.osprey/actions/runs/11198716239/job/31130227366#step:7:6010

**Comment by m7pr** [comment]
Thanks @gaborcsardi - thanks for poiniting to https://github.com/r-lib/pak/issues/702
