### ISSUE TITLE
Error: `gh: command not found`

### ISSUE THREAD

**Issue by pawelru** [r-hub/actions#25]
I have a package that has a training `.qmd` training materials in its `inst/` directory. That file is included in build ignore.

`r-hub/actions/setup-deps@v1` calls `r-lib/actions/setup-r-dependencies@v2` with it's default `install-quarto: 'auto'` which as a result detects that file and tries to install quarto and it fails as `gh` is not installed in many machines.

![image](https://github.com/user-attachments/assets/7b48232b-7cba-4a61-b366-2c1cc4d8521a)

Is it sensible to disable quarto install for good in here? Or alternatively - can you open and pass `install-quarto` parameter?

**Comment by gaborcsardi** [comment]
Yes, let's disable quarto for now, until we have a better way to install it, that works w/o gh.

**Comment by pawelru** [comment]
related: https://github.com/r-hub/rhub/issues/638 (if not duplicate - sorry!)
