### ISSUE TITLE
Ubuntu no longer has R preinstalled on GHA

### ISSUE THREAD

**Issue by krlmlr** [r-hub/actions#27]
- Leads to failures of the form `line 2: R: command not found`: https://github.com/duckdb/duckdb-r/actions/runs/11339400883
- Worked around by adding a "set up R" step in my `rhub.yaml`: https://github.com/duckdb/duckdb-r/actions/runs/11339432242

Should perhaps be the responsibility of this action?

**Comment by gaborcsardi** [comment]
Should be fixed now in `r-hub/actions@v1` via https://github.com/r-hub/actions/commit/5f4956cc52ff95ec99a0444a3b9bfd621bcd60f4
