### ISSUE TITLE
`macos-arm64` fails with `symbol not found in flat namespace '_ps__list_apps'`

### ISSUE THREAD

**Issue by pawelru** [r-hub/actions#28]
Observed for `r-release-macos-arm64` and `r-oldrel-macos-arm64`
Step: `Run r-hub/actions/setup-deps@v1`
```
Dependency resolution
  Error in dyn.load(dll_file) : 
    unable to load shared object '/private/var/folders/g6/rgtlsw6n123b0gt5483s5_cm0000gn/T/RtmpafSxCY/file1ee56fa0ad26/ps/libs//ps.so':
    dlopen(/private/var/folders/g6/rgtlsw6n123b0gt5483s5_cm0000gn/T/RtmpafSxCY/file1ee56fa0ad26/ps/libs//ps.so, 0x0006): symbol not found in flat namespace '_ps__list_apps'
  Calls: <Anonymous> ... load_private_packages -> load_private_package -> dyn.load
  Execution halted
```

This is a common failure across multiple (if not all) of pkgs that uses rhub workflows. Few examples: [[1]](https://github.com/insightsengineering/roxy.shinylive/actions/runs/11875716279/job/33125142616), [[2]](https://github.com/insightsengineering/tern.rbmi/actions/runs/11885263587/job/33120735394), [[3]](https://github.com/insightsengineering/formatters/actions/runs/11875714955/job/33093243393)

Re-run didn't help.

That must be a recent change. The same workflow (on the same R package codebase) succeeded last week.

Appreciate your help on this.

**Comment by gaborcsardi** [comment]
Seems like a bug in the devel pak build.

**Comment by gaborcsardi** [comment]
I'll move this over to pak. EDIT: actually, never mind, I cannot. Will fix in a minute.

**Comment by gaborcsardi** [comment]
This was a bug in the pak nightly builds, which were not prepared for Objective-C files when cross compiling for arm64 macOS on x86_64 macOS. 
Fixed here:
https://github.com/r-lib/pak/commit/fe4d2c6da65d534780cf73371819814cfeb81b57

I also removed the cross compiling, no need for that now that GHA has native arm64 macs:
https://github.com/r-lib/pak/commit/659fbf1f12094d2dd2e228930f78282b6a3bc647
https://github.com/r-lib/pak/commit/e7d20861baebd54c2412530a12e781c1e99066d3

I started a new build, I'll comment here when the new versions are deployed:
https://github.com/r-lib/pak/actions/runs/11890375962/job/33128891191

**Comment by gaborcsardi** [comment]
The new binaries are deployed, so this should be fixed now. Thanks for the report!

**Comment by pawelru** [comment]
I re-run the failed workflows and I confirm - all is looking good now! Thank you for the prompt action!

**Comment by gaborcsardi** [comment]
For the record, this is going to get better soon:
* first, now that I am not cross-compiling I can actually test that the build works,
* second, r-hub actions will switch to stable pak after the next pak release, instead of using the nightly builds.
