### ISSUE TITLE
Problem compiling fortran on macOS-latest (release)?

### ISSUE THREAD

**Issue by cjvanlissa** [r-hub/actions#7]
Dear all, I am using the `"check-standard"` setup to run R-CMD-check on a package with Fortran code, and the check fails for macOS-latest. At first glance, it seems to me that the Fortran compiler is not in place. Is this an error on my part, a bug, or a known limitation? 

Here is the failing test: https://github.com/cjvanlissa/bain/runs/1828646234?check_suite_focus=true

**Comment by gaborcsardi** [comment]
Did you mean to submit this in the r-lib/actions repository?

**Comment by cjvanlissa** [comment]
Yes I did.. is that not this?

**Comment by cjvanlissa** [comment]
Ah, I see I am suffering from morning dyslexia. My apologies...
